module rmn_misc_helpers
  use ISO_C_BINDING
  implicit none
#define IN_FORTRAN_CODE
#include <rmn/misc_operators.h>
#include <rmn/misc_pack.h>
#include <misc_swizzle.h>
#include <pack_stream.h>
#include <rmn/lorenzo.h>
#include <cpu_type.h>
#include <idwt53.h>
#include <smooth124.h>
end module
